name: build.yml
on:
  workflow_call: 
    inputs: 
      DOTNET_VERSION:
        required: true
        type: string
      PATH:
        required: true
        type: string
      SERVICE:
        required: true
        type: string
      DLL:
        required: true
        type: string
      SECRET:
        required: true
        type: string
        
env:
  PROJECT_ID: awtor-sheduler
  GAR_LOCATION: europe-west1
  REPOSITORY: docker
  REGION: europe-west1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}
          
      - name: 'Publish'
        shell: bash
        run: 'dotnet publish ${{ inputs.PATH }} -c Release -o ./out'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: 'github-deploy@${{ env.PROJECT_ID }}.iam.gserviceaccount.com' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        working-directory: ./out
        run: |-
          echo 'FROM mcr.microsoft.com/dotnet/aspnet:8.0' > Dockerfile
          echo 'COPY ./ /app' >> Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'ENTRYPOINT ["dotnet", "./${{ inputs.DLL }}", "--urls=http://0.0.0.0:8080"]' >> Dockerfile
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ inputs.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ inputs.SERVICE }}:${{ github.sha }}"

      - name: Deploy Api
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.SERVICE }}
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ inputs.SERVICE }}:${{ github.sha }}
          secrets: /home/appsettings=${{ inputs.SECRET }}:latest
