name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: awtor-sheduler
  GAR_LOCATION: europe-west1
  REPOSITORY: docker
  REGION: europe-west1
  NODE_VERSION: '20.x'  

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      DOTNET_VERSION: 8.0
      
  deploy-worker:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: worker

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: 'github-deploy@${{ env.PROJECT_ID }}.iam.gserviceaccount.com' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Deploy Sheduler.Worker
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        with:
          name: 'worker'
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          runtime: 'dotnet8'
          source_dir: ./
          entry_point: Worker
          cpu: 0.5
          memory: 512M
          service_account: app-runner@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
  
  deploy-api:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Download backend artifacts
        uses: actions/download-artifact@v4
        with:
          name: api

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: 'github-deploy@${{ env.PROJECT_ID }}.iam.gserviceaccount.com' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Deploy Api
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: management-api
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          source: ./
