name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

jobs:
  api:
    uses: ./.github/workflows/buildAndDeploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      DOTNET_VERSION: 8.0
      SERVICE: "sheduler-api${{ github.ref == 'refs/heads/main' && '-prod' || '-dev' }}"
      SECRET: "appsettings${{ github.ref == 'refs/heads/main' && '-prod' || '-dev' }}"
      DLL: 'Sheduler.Management.dll'
      PATH: ./App/Sheduler.Management/
  
  worker:
    uses: ./.github/workflows/buildAndDeploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      DOTNET_VERSION: 8.0
      SERVICE: "sheduler-worker${{ github.ref == 'refs/heads/main' && '-prod' || '-dev' }}"
      SECRET: "appsettings${{ github.ref == 'refs/heads/main' && '-prod' || '-dev' }}"
      DLL: 'Sheduler.Worker.dll'
      PATH: ./App/Sheduler.Worker/
