name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: awtor-sheduler
  GAR_LOCATION: europe-west1
  REPOSITORY: docker
  REGION: europe-west1

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      DOTNET_VERSION: 8.0
  
  deploy-worker:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      SERVICE: "sheduler-worker"
      PROJECT_ID: awtor-sheduler
      GAR_LOCATION: europe-west1
      REPOSITORY: docker
      REGION: europe-west1
      DLL: 'Sheduler.Worker.dll'
      artifact: worker
      
  deploy-api:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with: 
      SERVICE: "sheduler-api"
      PROJECT_ID: awtor-sheduler
      GAR_LOCATION: europe-west1
      REPOSITORY: docker
      REGION: europe-west1
      DLL: 'Sheduler.Management.dll'
      artifact: api
