name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

env:
  POSTFIX: ${{ github.ref == 'refs/heads/main' && '' || '-dev' }}

jobs:
  api:
    uses: ./.github/workflows/buildAndDeploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      DOTNET_VERSION: 8.0
      SERVICE: "sheduler-api"
      DLL: 'Sheduler.Management'
      PATH: ./App/Sheduler.Management/
  
  worker:
    uses: ./.github/workflows/buildAndDeploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      DOTNET_VERSION: 8.0
      SERVICE: "sheduler-worker${{ env.POSTFIX }}"
      SECRET: "appsettings${{ env.POSTFIX }}"
      DLL: 'Sheduler.Worker'
      PATH: ./App/Sheduler.Worker/
