name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      DOTNET_VERSION: 8.0
  
  deploy-worker:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      SERVICE: "sheduler-worker"
      DLL: 'Sheduler.Worker'
      artifact: worker
      
  deploy-api:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions:
      contents: 'read'
      id-token: 'write'
    with: 
      SERVICE: "sheduler-api"
      DLL: 'Sheduler.Management'
      artifact: api
